//! Trust tier enforcement for MCP tool dispatch.
//!
//! Maps each MCP tool to a required [`TrustTier`], resolves the connecting
//! agent's tier from config, and enforces access control with audit logging
//! and rate limiting for destructive operations.

use std::collections::{HashMap, HashSet};
use std::sync::Mutex;
use std::time::Instant;

use therminal_core::config::{TrustConfig, TrustTier};
use tracing::{info, warn};

// ── Required tier per tool ──────────────────────────────────────────────

/// Permission level required to invoke a given MCP tool.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ToolCategory {
    /// Read-only tools: terminal.sessions.list, terminal.sessions.get, terminal.panes.get_content.
    Observer,
    /// Write tools: terminal.sessions.create, terminal.panes.write.
    Writer,
    /// Destructive tools: terminal.sessions.destroy.
    Admin,
}

impl ToolCategory {
    /// The minimum [`TrustTier`] required for this category.
    pub fn required_tier(self) -> TrustTier {
        match self {
            Self::Observer => TrustTier::Sandboxed,
            Self::Writer => TrustTier::Supervised,
            Self::Admin => TrustTier::Trusted,
        }
    }
}

/// Classify an MCP tool name into its permission category.
///
/// Returns `None` for unknown tool names (handled separately as invalid).
pub fn tool_category(tool_name: &str) -> Option<ToolCategory> {
    match tool_name {
        "terminal.sessions.list"
        | "terminal.sessions.get"
        | "terminal.panes.list"
        | "terminal.panes.get_geometry"
        | "terminal.panes.get_content"
        | "terminal.panes.get_summary"
        | "terminal.panes.peek"
        | "terminal.panes.wait_for_output"
        | "terminal.panes.capture_result"
        | "terminal.panes.query_events"
        | "terminal.semantic.query_history"
        | "terminal.semantic.query_commands"
        | "terminal.semantic.get_hotspots"
        | "terminal.workspaces.list"
        | "terminal.workspaces.get_layout"
        | "terminal.agents.list"
        | "terminal.agents.get_details"
        | "terminal.agents.get_status"
        | "terminal.agents.get_session_detail"
        | "terminal.agents.get_cadence"
        | "terminal.agents.find_with_capacity"
        | "terminal.patterns.stats"
        | "terminal.events.stats" => Some(ToolCategory::Observer),
        "terminal.sessions.create"
        | "terminal.panes.write"
        | "terminal.panes.create"
        | "terminal.panes.create_tail"
        | "terminal.panes.tag"
        | "terminal.panes.untag" => Some(ToolCategory::Writer),
        "terminal.sessions.destroy" | "terminal.panes.destroy" => Some(ToolCategory::Admin),
        _ => None,
    }
}

/// Classify an MCP resource URI into its permission category.
///
/// All resource reads are Observer-tier (read-only). Returns `None` for
/// URIs that don't match any known resource pattern.
pub fn resource_category(uri: &str) -> Option<ToolCategory> {
    if uri.starts_with("terminal://pane/")
        || uri.starts_with("terminal://events")
        || uri.starts_with("therminal://claude/")
        || uri.starts_with("therminal://agents/")
    {
        Some(ToolCategory::Observer)
    } else {
        None
    }
}

/// Run the trust gate for an MCP resource access.
///
/// Resources are Observer-tier (read-only). The check resolves the agent's
/// tier and verifies it meets the Observer minimum.
pub fn check_resource_access(
    uri: &str,
    agent: &AgentIdentity,
    config: &TrustConfig,
) -> TrustCheckResult {
    let category = match resource_category(uri) {
        Some(c) => c,
        None => {
            audit_log(agent, uri, "unknown_resource");
            return TrustCheckResult::Allowed;
        }
    };

    let agent_tier = agent.resolve_tier(config);
    let required = category.required_tier();

    if !agent_tier.has_access(required) {
        let reason = format!(
            "permission denied: agent {:?} has tier {:?}, resource {:?} requires {:?}",
            agent.name, agent_tier, uri, required,
        );
        audit_log_denied(agent, uri, &reason);
        return TrustCheckResult::Denied(reason);
    }

    audit_log(agent, uri, "allowed");
    TrustCheckResult::Allowed
}

// ── Agent identity resolution ───────────────────────────────────────────

/// Resolved identity of an MCP client.
///
/// `connection_id` is the daemon-assigned per-connection identifier used as
/// the trust key for session-scoped grants. Unlike `name` (which is
/// self-reported by the client during the MCP `initialize` handshake and
/// therefore spoofable), `connection_id` is generated by the daemon at accept
/// time and cannot be forged across connections.
///
/// `name` is retained for display, audit logs, and tier resolution from the
/// `[trust.agents.*]` config — but never as the primary key for grants.
/// (tn-yuu4)
#[derive(Debug, Clone)]
pub struct AgentIdentity {
    /// Agent name as reported by the MCP client's `Implementation.name`,
    /// or `"unknown"` if not available. **Display / config-lookup only —
    /// never the trust key for session grants.**
    pub name: String,
    /// Daemon-assigned connection identifier. Unique per accepted MCP
    /// connection within the daemon's lifetime. This is the only identifier
    /// used to key session-scoped grants in [`SessionGrants`].
    pub connection_id: u64,
}

impl AgentIdentity {
    /// Resolve the agent's [`TrustTier`] by looking up its name in the
    /// per-agent config map, falling back to `default_tier`.
    ///
    /// Tier resolution still uses the self-reported `name` because the
    /// `[trust.agents.*]` config is keyed by friendly agent names. This is
    /// safe because tier-from-name only ever *grants* the configured tier;
    /// the worst a name spoof can do at this layer is downgrade the
    /// attacker into the configured tier for the impersonated agent. The
    /// per-connection grant escalation path is the actual security boundary
    /// and is keyed off [`Self::connection_id`].
    pub fn resolve_tier(&self, config: &TrustConfig) -> TrustTier {
        config
            .agents
            .get(&self.name)
            .map(|a| a.tier)
            .unwrap_or(config.default_tier)
    }
}

// ── Rate limiter ────────────────────────────────────────────────────────

/// Simple sliding-window rate limiter for destructive operations.
///
/// Tracks timestamps of recent invocations per agent name and rejects
/// calls that exceed the configured maximum per minute.
pub struct RateLimiter {
    /// Max operations per minute per agent. `0` means unlimited.
    max_per_minute: u32,
    /// Per-agent timestamps of recent destructive operations.
    windows: Mutex<HashMap<String, Vec<Instant>>>,
}

impl RateLimiter {
    /// Create a new rate limiter with the given per-minute cap.
    pub fn new(max_per_minute: u32) -> Self {
        Self {
            max_per_minute,
            windows: Mutex::new(HashMap::new()),
        }
    }

    /// Check whether the agent is allowed to perform a destructive operation.
    ///
    /// Returns `Ok(())` if allowed, or `Err(message)` if rate-limited.
    /// Automatically records the invocation on success.
    pub fn check_and_record(&self, agent_name: &str) -> Result<(), String> {
        if self.max_per_minute == 0 {
            return Ok(()); // Unlimited
        }

        let mut windows = self.windows.lock().unwrap_or_else(|e| e.into_inner());
        let now = Instant::now();
        let one_minute_ago = now - std::time::Duration::from_secs(60);

        let timestamps = windows.entry(agent_name.to_string()).or_default();

        // Prune entries older than 1 minute.
        timestamps.retain(|t| *t > one_minute_ago);

        if timestamps.len() as u32 >= self.max_per_minute {
            Err(format!(
                "rate limit exceeded: agent {:?} has reached {} destructive operations per minute",
                agent_name, self.max_per_minute,
            ))
        } else {
            timestamps.push(now);
            Ok(())
        }
    }

    /// Update the rate limit cap (e.g. on config hot-reload).
    pub fn set_max_per_minute(&mut self, max: u32) {
        self.max_per_minute = max;
    }
}

// ── Trust gate (combines all checks) ───────────────────────────────────

/// Result of a trust enforcement check.
#[derive(Debug)]
pub enum TrustCheckResult {
    /// Tool call is allowed.
    Allowed,
    /// Tool call is denied with a reason.
    Denied(String),
    /// Tool call requires user approval via the GUI modal (tn-b99).
    Escalation {
        /// Agent name requesting the tool.
        agent_name: String,
        /// The MCP tool being requested.
        tool_name: String,
        /// The agent's current trust tier.
        current_tier: TrustTier,
        /// The tier required by the tool.
        required_tier: TrustTier,
    },
}

// -- Session-scoped grants (tn-b99 / tn-yuu4) --

/// Tracks tools temporarily approved during this daemon session, keyed by
/// the daemon-assigned **connection id**, never by the client-supplied agent
/// name. Populated by user approval via the trust escalation modal.
///
/// Keying on connection id (rather than agent name) means a fresh connection
/// always starts with an empty grant set, even if the new client claims the
/// `Implementation.name` of a previously-approved agent. The agent name is
/// only retained on the [`AgentIdentity`] struct for display in audit logs
/// and tier resolution.
pub struct SessionGrants {
    grants: Mutex<HashSet<(u64, String)>>,
}

impl Default for SessionGrants {
    fn default() -> Self {
        Self {
            grants: Mutex::new(HashSet::new()),
        }
    }
}

impl SessionGrants {
    /// Create an empty grant set.
    pub fn new() -> Self {
        Self::default()
    }

    /// Record a session-scoped grant for the given connection + tool.
    ///
    /// `agent_name` is for the audit-log line only and is never stored as
    /// part of the trust key. (tn-yuu4)
    pub fn grant(&self, connection_id: u64, agent_name: &str, tool_name: &str) {
        let mut g = self.grants.lock().unwrap_or_else(|e| e.into_inner());
        g.insert((connection_id, tool_name.to_string()));
        info!(
            connection_id = %connection_id,
            agent = %agent_name,
            tool = %tool_name,
            "trust escalation approved (session grant)"
        );
    }

    /// Check whether the given connection has a session-scoped grant for
    /// this tool. (tn-yuu4)
    pub fn has_grant(&self, connection_id: u64, tool_name: &str) -> bool {
        let g = self.grants.lock().unwrap_or_else(|e| e.into_inner());
        g.contains(&(connection_id, tool_name.to_string()))
    }
}

/// Run the full trust gate for an MCP tool invocation.
///
/// 1. Resolve agent tier from config.
/// 2. Check tier against required level.
/// 3. For destructive tools, apply rate limiting.
/// 4. Audit-log the result.
pub fn check_tool_access(
    tool_name: &str,
    agent: &AgentIdentity,
    config: &TrustConfig,
    rate_limiter: &RateLimiter,
) -> TrustCheckResult {
    check_tool_access_with_grants(tool_name, agent, config, rate_limiter, None)
}

/// Like [`check_tool_access`] but checks session grants and emits
/// [`TrustCheckResult::Escalation`] when the GUI can prompt the user.
pub fn check_tool_access_with_grants(
    tool_name: &str,
    agent: &AgentIdentity,
    config: &TrustConfig,
    rate_limiter: &RateLimiter,
    session_grants: Option<&SessionGrants>,
) -> TrustCheckResult {
    let category = match tool_category(tool_name) {
        Some(c) => c,
        None => {
            audit_log(agent, tool_name, "unknown_tool");
            return TrustCheckResult::Allowed;
        }
    };

    let agent_tier = agent.resolve_tier(config);
    let required = category.required_tier();

    if !agent_tier.has_access(required) {
        if let Some(grants) = session_grants {
            // tn-yuu4: grant lookup is keyed by the daemon-assigned
            // connection id, NOT by the client-supplied `agent.name`.
            if grants.has_grant(agent.connection_id, tool_name) {
                audit_log(agent, tool_name, "allowed_via_session_grant");
            } else if let Some(auto_tier) = config.auto_approve_tier {
                if auto_tier.has_access(required) {
                    audit_log(agent, tool_name, "auto_approved");
                } else {
                    audit_log(agent, tool_name, "escalation_requested");
                    return TrustCheckResult::Escalation {
                        agent_name: agent.name.clone(),
                        tool_name: tool_name.to_string(),
                        current_tier: agent_tier,
                        required_tier: required,
                    };
                }
            } else {
                audit_log(agent, tool_name, "escalation_requested");
                return TrustCheckResult::Escalation {
                    agent_name: agent.name.clone(),
                    tool_name: tool_name.to_string(),
                    current_tier: agent_tier,
                    required_tier: required,
                };
            }
        } else {
            let reason = format!(
                "permission denied: agent {:?} has tier {:?}, tool {:?} requires {:?}",
                agent.name, agent_tier, tool_name, required,
            );
            audit_log_denied(agent, tool_name, &reason);
            return TrustCheckResult::Denied(reason);
        }
    }

    if let Some(agent_cfg) = config.agents.get(&agent.name)
        && let Some(allowed) = &agent_cfg.allowed_tools
        && !allowed.iter().any(|t| t == tool_name)
    {
        let reason = format!(
            "tool not in agent allowlist: agent {:?} attempted {:?}",
            agent.name, tool_name,
        );
        audit_log_denied(agent, tool_name, &reason);
        return TrustCheckResult::Denied(reason);
    }

    if category == ToolCategory::Admin
        && let Err(reason) = rate_limiter.check_and_record(&agent.name)
    {
        audit_log_denied(agent, tool_name, &reason);
        return TrustCheckResult::Denied(reason);
    }

    audit_log(agent, tool_name, "allowed");
    TrustCheckResult::Allowed
}

// ── Audit logging ──────────────────────────────────────────────────────

fn audit_log(agent: &AgentIdentity, tool: &str, result: &str) {
    info!(
        agent = %agent.name,
        connection_id = %agent.connection_id,
        tool = %tool,
        result = %result,
        "MCP tool invocation"
    );
}

fn audit_log_denied(agent: &AgentIdentity, tool: &str, reason: &str) {
    warn!(
        agent = %agent.name,
        connection_id = %agent.connection_id,
        tool = %tool,
        reason = %reason,
        "MCP tool invocation denied"
    );
}

// ── Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use therminal_core::config::AgentTrust;

    /// Build a test [`AgentIdentity`] with the given name and a fixed
    /// connection id of 0. The bulk of the legacy tests don't exercise the
    /// session-grant path, so a constant id is fine; tests that DO care
    /// about per-connection isolation construct identities directly.
    fn agent(name: &str) -> AgentIdentity {
        AgentIdentity {
            name: name.to_string(),
            connection_id: 0,
        }
    }

    #[test]
    fn tier_ordering() {
        assert!(TrustTier::Sandboxed < TrustTier::Supervised);
        assert!(TrustTier::Supervised < TrustTier::Trusted);
    }

    #[test]
    fn has_access() {
        assert!(TrustTier::Trusted.has_access(TrustTier::Sandboxed));
        assert!(TrustTier::Trusted.has_access(TrustTier::Trusted));
        assert!(TrustTier::Supervised.has_access(TrustTier::Sandboxed));
        assert!(!TrustTier::Sandboxed.has_access(TrustTier::Supervised));
        assert!(!TrustTier::Supervised.has_access(TrustTier::Trusted));
    }

    #[test]
    fn tool_categories() {
        assert_eq!(
            tool_category("terminal.sessions.list"),
            Some(ToolCategory::Observer)
        );
        assert_eq!(
            tool_category("terminal.sessions.get"),
            Some(ToolCategory::Observer)
        );
        assert_eq!(
            tool_category("terminal.panes.list"),
            Some(ToolCategory::Observer)
        );
        assert_eq!(
            tool_category("terminal.panes.get_geometry"),
            Some(ToolCategory::Observer)
        );
        assert_eq!(
            tool_category("terminal.panes.get_content"),
            Some(ToolCategory::Observer)
        );
        assert_eq!(
            tool_category("terminal.semantic.query_history"),
            Some(ToolCategory::Observer)
        );
        assert_eq!(
            tool_category("terminal.semantic.query_commands"),
            Some(ToolCategory::Observer)
        );
        assert_eq!(
            tool_category("terminal.semantic.get_hotspots"),
            Some(ToolCategory::Observer)
        );
        assert_eq!(
            tool_category("terminal.workspaces.list"),
            Some(ToolCategory::Observer)
        );
        assert_eq!(
            tool_category("terminal.sessions.create"),
            Some(ToolCategory::Writer)
        );
        assert_eq!(
            tool_category("terminal.panes.create"),
            Some(ToolCategory::Writer)
        );
        assert_eq!(
            tool_category("terminal.panes.write"),
            Some(ToolCategory::Writer)
        );
        assert_eq!(
            tool_category("terminal.sessions.destroy"),
            Some(ToolCategory::Admin)
        );
        assert_eq!(
            tool_category("terminal.panes.destroy"),
            Some(ToolCategory::Admin)
        );
        assert_eq!(tool_category("nonexistent"), None);
    }

    #[test]
    fn resolve_tier_default() {
        let config = TrustConfig::default();
        let agent = agent("unknown-agent");
        assert_eq!(agent.resolve_tier(&config), TrustTier::Supervised);
    }

    #[test]
    fn resolve_tier_per_agent() {
        let mut config = TrustConfig::default();
        config.agents.insert(
            "claude".to_string(),
            AgentTrust {
                tier: TrustTier::Trusted,
                allowed_tools: None,
            },
        );
        let agent = agent("claude");
        assert_eq!(agent.resolve_tier(&config), TrustTier::Trusted);
    }

    #[test]
    fn rate_limiter_allows_within_limit() {
        let limiter = RateLimiter::new(3);
        assert!(limiter.check_and_record("agent1").is_ok());
        assert!(limiter.check_and_record("agent1").is_ok());
        assert!(limiter.check_and_record("agent1").is_ok());
        assert!(limiter.check_and_record("agent1").is_err());
        // Different agent is independent.
        assert!(limiter.check_and_record("agent2").is_ok());
    }

    #[test]
    fn rate_limiter_zero_is_unlimited() {
        let limiter = RateLimiter::new(0);
        for _ in 0..100 {
            assert!(limiter.check_and_record("agent").is_ok());
        }
    }

    #[test]
    fn check_tool_access_sandboxed_can_read() {
        let config = TrustConfig {
            default_tier: TrustTier::Sandboxed,
            ..TrustConfig::default()
        };
        let agent = agent("test");
        let limiter = RateLimiter::new(5);
        assert!(matches!(
            check_tool_access("terminal.sessions.list", &agent, &config, &limiter),
            TrustCheckResult::Allowed
        ));
    }

    #[test]
    fn check_tool_access_sandboxed_cannot_write() {
        let config = TrustConfig {
            default_tier: TrustTier::Sandboxed,
            ..TrustConfig::default()
        };
        let agent = agent("test");
        let limiter = RateLimiter::new(5);
        assert!(matches!(
            check_tool_access("terminal.sessions.create", &agent, &config, &limiter),
            TrustCheckResult::Denied(_)
        ));
    }

    #[test]
    fn check_tool_access_supervised_cannot_destroy() {
        let config = TrustConfig {
            default_tier: TrustTier::Supervised,
            ..TrustConfig::default()
        };
        let agent = agent("test");
        let limiter = RateLimiter::new(5);
        assert!(matches!(
            check_tool_access("terminal.sessions.destroy", &agent, &config, &limiter),
            TrustCheckResult::Denied(_)
        ));
    }

    #[test]
    fn check_tool_access_trusted_can_destroy() {
        let config = TrustConfig {
            default_tier: TrustTier::Trusted,
            ..TrustConfig::default()
        };
        let agent = agent("test");
        let limiter = RateLimiter::new(5);
        assert!(matches!(
            check_tool_access("terminal.sessions.destroy", &agent, &config, &limiter),
            TrustCheckResult::Allowed
        ));
    }

    #[test]
    fn check_tool_access_rate_limited() {
        let config = TrustConfig {
            default_tier: TrustTier::Trusted,
            ..TrustConfig::default()
        };
        let agent = agent("test");
        let limiter = RateLimiter::new(1);
        assert!(matches!(
            check_tool_access("terminal.sessions.destroy", &agent, &config, &limiter),
            TrustCheckResult::Allowed
        ));
        assert!(matches!(
            check_tool_access("terminal.sessions.destroy", &agent, &config, &limiter),
            TrustCheckResult::Denied(_)
        ));
    }

    #[test]
    fn resource_categories() {
        assert_eq!(
            resource_category("terminal://pane/1/content"),
            Some(ToolCategory::Observer)
        );
        assert_eq!(
            resource_category("terminal://pane/42/output"),
            Some(ToolCategory::Observer)
        );
        assert_eq!(resource_category("file:///tmp/foo"), None);
        assert_eq!(resource_category("unknown://something"), None);
        assert_eq!(
            resource_category("therminal://claude/events"),
            Some(ToolCategory::Observer)
        );
        assert_eq!(
            resource_category("therminal://claude/events/abc123"),
            Some(ToolCategory::Observer)
        );
    }

    #[test]
    fn check_resource_access_sandboxed_allowed() {
        let config = TrustConfig {
            default_tier: TrustTier::Sandboxed,
            ..TrustConfig::default()
        };
        let agent = agent("test");
        assert!(matches!(
            check_resource_access("terminal://pane/1/content", &agent, &config),
            TrustCheckResult::Allowed
        ));
    }

    #[test]
    fn allowlist_none_imposes_no_restriction() {
        let mut config = TrustConfig {
            default_tier: TrustTier::Trusted,
            ..TrustConfig::default()
        };
        config.agents.insert(
            "claude".to_string(),
            AgentTrust {
                tier: TrustTier::Trusted,
                allowed_tools: None,
            },
        );
        let agent = agent("claude");
        let limiter = RateLimiter::new(5);
        assert!(matches!(
            check_tool_access("terminal.sessions.list", &agent, &config, &limiter),
            TrustCheckResult::Allowed
        ));
    }

    #[test]
    fn allowlist_empty_denies_all() {
        let mut config = TrustConfig {
            default_tier: TrustTier::Trusted,
            ..TrustConfig::default()
        };
        config.agents.insert(
            "claude".to_string(),
            AgentTrust {
                tier: TrustTier::Trusted,
                allowed_tools: Some(vec![]),
            },
        );
        let agent = agent("claude");
        let limiter = RateLimiter::new(5);
        assert!(matches!(
            check_tool_access("terminal.sessions.list", &agent, &config, &limiter),
            TrustCheckResult::Denied(_)
        ));
    }

    #[test]
    fn allowlist_specific_tool_allows_listed_denies_others() {
        let mut config = TrustConfig {
            default_tier: TrustTier::Trusted,
            ..TrustConfig::default()
        };
        config.agents.insert(
            "claude".to_string(),
            AgentTrust {
                tier: TrustTier::Trusted,
                allowed_tools: Some(vec!["terminal.sessions.list".to_string()]),
            },
        );
        let agent = agent("claude");
        let limiter = RateLimiter::new(5);
        assert!(matches!(
            check_tool_access("terminal.sessions.list", &agent, &config, &limiter),
            TrustCheckResult::Allowed
        ));
        assert!(matches!(
            check_tool_access("terminal.panes.list", &agent, &config, &limiter),
            TrustCheckResult::Denied(_)
        ));
    }

    #[test]
    fn check_resource_access_unknown_uri_allowed() {
        let config = TrustConfig::default();
        let agent = agent("test");
        // Unknown URIs pass through (handled as not-found by the handler).
        assert!(matches!(
            check_resource_access("file:///tmp/foo", &agent, &config),
            TrustCheckResult::Allowed
        ));
    }

    // ── tn-yuu4: SessionGrants are keyed by connection id ─────────────

    #[test]
    fn session_grants_keyed_by_connection_id_not_agent_name() {
        // A session grant recorded for connection 1 must NOT be visible to
        // a different connection (id 2), even if the new connection claims
        // the same client-supplied agent name.
        let grants = SessionGrants::new();
        grants.grant(1, "claude", "terminal.sessions.destroy");

        // Same connection — has the grant.
        assert!(grants.has_grant(1, "terminal.sessions.destroy"));

        // Different connection — must NOT inherit the grant, even though
        // the attacker can freely re-use the "claude" agent name on the
        // wire (the agent name is not part of the trust key).
        assert!(!grants.has_grant(2, "terminal.sessions.destroy"));

        // Different tool, same connection — also denied.
        assert!(!grants.has_grant(1, "terminal.panes.write"));
    }

    #[test]
    fn check_tool_access_session_grant_does_not_leak_across_connections() {
        // End-to-end regression: drive the full
        // `check_tool_access_with_grants` path with two different
        // `AgentIdentity`s that share a `name` but differ on
        // `connection_id`. A grant approved for connection 1 must not
        // satisfy the trust gate for connection 2.
        let config = TrustConfig {
            default_tier: TrustTier::Sandboxed, // Cannot destroy by tier.
            ..TrustConfig::default()
        };
        let limiter = RateLimiter::new(100);
        let grants = SessionGrants::new();

        // Connection 1: gets approval for terminal.sessions.destroy.
        let agent_a = AgentIdentity {
            name: "claude".to_string(),
            connection_id: 1,
        };
        grants.grant(
            agent_a.connection_id,
            &agent_a.name,
            "terminal.sessions.destroy",
        );
        assert!(matches!(
            check_tool_access_with_grants(
                "terminal.sessions.destroy",
                &agent_a,
                &config,
                &limiter,
                Some(&grants),
            ),
            TrustCheckResult::Allowed
        ));

        // Connection 2: same advertised name, different connection id.
        // Without auto_approve_tier the result must be `Escalation` (i.e.
        // the user is asked again), never `Allowed` via the prior grant.
        let agent_b = AgentIdentity {
            name: "claude".to_string(),
            connection_id: 2,
        };
        let result = check_tool_access_with_grants(
            "terminal.sessions.destroy",
            &agent_b,
            &config,
            &limiter,
            Some(&grants),
        );
        assert!(
            matches!(result, TrustCheckResult::Escalation { .. }),
            "spoofed agent name on a new connection must NOT inherit prior session grants; got {result:?}"
        );
    }
}
